### ISSUE TITLE
Crash NullPointerException, void com.adcolony.sdk.AdColonyInterstitialListener.onRequestNotFilled(com.adcolony.sdk.AdColonyZone)

### ISSUE THREAD

**Issue by valeravovnov** [AdColony/AdColony-Android-SDK#76]
Hi,
I have the following crash on version 4.1.1

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.adcolony.sdk.AdColonyInterstitialListener.onRequestNotFilled(com.adcolony.sdk.AdColonyZone)' on a null object reference
       at com.adcolony.sdk.AdColony.requestInterstitial(SourceFile:796)
       at com.adcolony.sdk.AdColony.requestInterstitial(SourceFile:753)
       at com.mopub.mobileads.AdColonyInterstitial$2.safedk_AdColony_requestInterstitial_b087ef50362f6276d8c451a09f009652(AdColonyInterstitial.java)
       at com.mopub.mobileads.AdColonyInterstitial$2.onExpiring(AdColonyInterstitial.java:178)
       at com.adcolony.sdk.d$11.run(SourceFile:295)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6119)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```
Operating system: 
Android 9 about 49%
Android 10 about 22%
Android 8 about 17%

**Comment by pchinn** [comment]
HI @valeravovnov,  The NPE was fixed with our recent v4.1.4 release.  A little more time is needed to get [Mopub](https://developers.mopub.com/publishers/mediation/integrate/) to update/support our v4.1.4.  Thanks.
